baseURL = "https://www.samkillermann.com/"
languageCode = "en-us"
title = "Sam Killermann's Blog"
enableRobotsTXT = true
canonifyURLs = true
summaryLength = 40

[Author]
	name = "Sam Killermann"

[taxonomies]
  category = "categories"
	topic = "topics"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
	author_patrons_count = 15
	site_patrons_count = 27
	email_list_url = "https://app.convertkit.com/landing_pages/402557?v=7"
	description = "Killermann is the author of several books, and his global justice resources are viewed and downloaded by millions of people every year. Here, he blogs."
	og_image = "/img/sK-social-card.png"

[social]
	twitter = "Killermann"

[menu]
	[[menu.main]]
		name = "Popular"
		url = "/popular/"
		pre = "heartbeat"
		weight = 1
	[[menu.main]]
		name = "Fresh"
		url = "/fresh/"
		pre = "air-freshener"
		weight = 2
	[[menu.main]]
		name = "Topics"
		url = "/topics/"
		pre = "shapes"
		weight = 3
	[[menu.main]]
		name = "Books"
		url = "/books/"
		pre = "books"
		weight = 4
	[[menu.main]]
		name = "About"
		url = "/about/"
		pre = "pencil-alt"
		weight = 5
	[[menu.main]]
		name = "Start Here"
		url = "/start-here/"
		pre = "compass"
		weight = 6
	[[menu.footer]]
		name = "Challenges"
		url = "/topics/challenge/"
		pre = "lightbulb"
		weight = 2
	[[menu.footer]]
		name = "Say Hi"
		url = "/contact/"
		pre = "kiss-wink-heart"
		weight = 2
	[[menu.footer]]
		name = "Subscribe"
		url = "/subscribe/"
		pre = "subscribe"
		weight = 3